APP_NAME=flow-office
APP_ENV=production
APP_KEY=${BACKEND_APP_KEY}
APP_DEBUG=false
APP_URL=${BACKEND_APP_URL}

# マウントパス自体が'api'セグメントを兼ねるため空にする(docs/27-release-runbook.md)
APP_API_PREFIX=

FRONTEND_URL=${FRONTEND_URL}

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=${BACKEND_DB_HOST}
DB_PORT=3306
DB_DATABASE=${BACKEND_DB_DATABASE}
DB_USERNAME=${BACKEND_DB_USERNAME}
DB_PASSWORD=${BACKEND_DB_PASSWORD}

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database

MAIL_MAILER=log
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"

# Entra ID資格情報はsystem_settings(DB)で管理するため、本番では設定しない
# (docs/06-usecases-auth.md, backend/.env.example参照)。
MICROSOFT_CLIENT_ID=
MICROSOFT_CLIENT_SECRET=
MICROSOFT_TENANT_ID=common
MICROSOFT_MOCK_ENABLED=false

L5_SWAGGER_GENERATE_ALWAYS=false
